### ISSUE TITLE
Is dates.json mandatory?

### ISSUE THREAD

**Issue by Depanshu-Sani** [VSainteuf/pytorch-psetae#12]
@VSainteuf, the following statement seems to mention that the dates.json file is not mandatory:
```The dates of the observations, if they are going to be used for the positional encoding, should be stored in YYYYMMDD format in the META/dates.json file```
I am using my own dataset which is collected according to the growing seasons of the crop, instead of a fixed duration. Hence, I am not using dates.json as it does not seem to be useful in this case. But it looks like this file is mandatory. I even tried putting the dates.json file loader in a conditional statement, but it's also not working.
Can you please confirm whether this file is necessary or not? And if yes, can you point me out to the reference which states its usage?

**Comment by VSainteuf** [comment]
Hi @Depanshu-Sani,
dates.json is used in my code to compute the positional encodings based on the observation dates instead of the position in the sequence.
It is accessed in line 70 of `dataset.py` and used line 188 of `train.py`.

So a quick workaround for you would be to comment l.70-71 of `dataset.py` and instead initialise the variable d as an empty dict. You can then pass the `--position order` argument to `train.py` and this should work. However doing so, the positional encodings will be based on the sequence ordering instead of the observation dates. 

You can also have a look at [this issue](https://github.com/VSainteuf/lightweight-temporal-attention-pytorch/issues/1#issuecomment-915196139) where I point to more recent code that can handle time series with different  date sequences.

**Comment by Depanshu-Sani** [comment]
Positional encoding based on the sequence order is exactly what I needed!
Thank you :)

**Comment by Depanshu-Sani** [comment]
I tried modifying the code as you mentioned but it seems that this not working. I commented line 70-73 (Ln 72 & 73 use the dates.json loaded in ln 70-71). I used the following command:
```
python train.py --dataset_folder ../Dataset/spatio-temporal/L8/SEASON_WISE/ --num_classes 2 --mlp1 [7,32,64] --mlp2 [128,128] --mlp4 [128,64,32,2] --geomfeat 0 --input_dim 7 --res_dir spatio-temporal/L8/SEASON_WISE --position order
```
**Error:**
```
Traceback (most recent call last):
  File "train.py", line 309, in <module>
    main(config)
  File "train.py", line 199, in main
    model = PseTae(**model_config)
  File "/home/depanshus/pytorch-psetae/models/stclassifier.py", line 26, in __init__
    T=T, len_max_seq=len_max_seq, positions=positions)
  File "/home/depanshus/pytorch-psetae/models/tae.py", line 47, in __init__
    positions = len_max_seq + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by VSainteuf** [comment]
Yes I forgot one thing: if you are not going to provide the list of dates, you need to specify the maximum length of sequence in your dataset (this does not have to be exact, an overestimation will do). This is done with the `--lms` argument of the `train.py` script.

**Comment by Depanshu-Sani** [comment]
It worked! Thanks for the quick response :)

**Comment by manapshymyr-OB** [comment]
@VSainteuf Hi, in this situation (where dates are not equal for the files) how should the normalization be calculated? Because the normalization has txc shape which t is time. I am a little bit confused. I am asking this because my dataset has not have all data for the dates extracted from my data

**Comment by manapshymyr-OB** [comment]
@Depanshu-Sani how did you calculate normalization if you do not have specific list of dates?
