### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by NourSoltani** [VSainteuf/pytorch-psetae#16]
Greetings Mr @VSainteuf 
I have a question about the inference if you may.
Is it an obligation to use the same T in the training and inference? Because I'm dealing with data that can have rotation(so if the class of the land changes, we'll not notice since, in the case of T=24, it'll be a new picture of class "1"  and the 23 other pictures will have the old class "0". So, basically the new picture will be meaningless. For that, I know it's a little bit weird but can I use only the last picture in the inference(T=1), or repeat this latter image 24 times(So it's like there's 24 different images)?
-Another question if you may :) Based on your experience, do you think that it's possible to work with this algorithm in urban stuff; Let's say to segment if there's building in the parcel or it's empty?

**Comment by VSainteuf** [comment]
Hi @NourSoltani ,
It's ok not to use the same number of dates at inference time. However, if T=1 at inference time, it doesn't seem relevant to train a model with temporal encoding since there is no temporal dimension at test time. 
I never tried PSE-TAE on urban datasets, I think it could work well. However, the pixel set setting is very specific to agricultural parcels. Maybe for an urban segmentation problem, it would be better to use a semantic segmentation architecture such as [U-TAE](https://github.com/VSainteuf/utae-paps).

**Comment by NourSoltani** [comment]
@VSainteuf  Thank you very much for your response.
The problem that prevents me to work with U-TAE is that I have already shapefiles for the zones I am working on: Each zone has its corresponding shapefile with the plygon coordinataes.
In my case: A parcel(lot) can contain a built-in part, and the rest of it will be empty for example: So, I'm willing to consider this parcel built-in. However, in the U-TAE,  I'm afraid that it will consider them as two independent parcels. Am I wrong?

**Comment by VSainteuf** [comment]
Ok if your AOI can be subdivided into parcels that make sense for your problem then yes PSE-TAE is a good idea. U-TAE will give you a prediction for each individual pixel.

**Comment by NourSoltani** [comment]
Thank you very  much for clarifying Mr @VSainteuf !!
